steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west8-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/drawings-to-latex/drawings-to-latex:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west8-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/drawings-to-latex/drawings-to-latex:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'drawings-to-latex'
      - '--image'
      - 'europe-west8-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/drawings-to-latex/drawings-to-latex:$COMMIT_SHA'
      - '--region'
      - 'europe-west8'
      - '--platform'
      - 'managed'
      - '--timeout'
      - '900'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'

images:
  - 'europe-west8-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/drawings-to-latex/drawings-to-latex:$COMMIT_SHA'